const fs = require('fs');
const path = require('path');

const tsvDir = path.join(__dirname, '../src/data/tsv');
const outDir = path.join(__dirname, '../src/data/phrases');

if (!fs.existsSync(tsvDir)) fs.mkdirSync(tsvDir, { recursive: true });
if (!fs.existsSync(outDir)) fs.mkdirSync(outDir, { recursive: true });

function compileTSV() {
    const files = fs.readdirSync(tsvDir).filter(f => f.endsWith('.tsv'));
    let globalCounter = 501; // Starting from chunk 11 (phrase 501)

    for (const file of files) {
        const chunkNumber = file.match(/\d+/)[0]; // e.g., 'chunk_011.tsv' -> '011'
        const content = fs.readFileSync(path.join(tsvDir, file), 'utf-8');
        const lines = content.split('\n').filter(line => line.trim() && !line.startsWith('//'));

        const chunkData = [];
        for (const line of lines) {
            const cols = line.split('\t').map(c => c.trim());
            if (cols.length < 13) continue; // Skip malformed lines

            // 0: ID, 1: Chinese, 2: Pinyin, 3: Japanese, 4: Category, 5: Level
            // 6: Spk1Name, 7: Spk1Avatar, 8: Spk1Exp, 9: Spk1Chn, 10: Spk1Pinyin, 11: Spk1Jpn
            // 12: Spk2Name, 13: Spk2Avatar, 14: Spk2Exp, 15: Spk2Chn, 16: Spk2Pinyin, 17: Spk2Jpn
            // 18: Notes (Optional)

            const phraseObj = {
                id: `phrase_m_${String(globalCounter).padStart(3, '0')}`,
                chinese: cols[0],
                pinyin: cols[1],
                japanese: cols[2],
                category: cols[3],
                level: parseInt(cols[4] || '1', 10),
                example: [
                    {
                        speaker: cols[6],
                        avatar: cols[7],
                        expression: cols[8],
                        chinese: cols[9],
                        pinyin: cols[10] || "Autogenerated",
                        japanese: cols[11]
                    },
                    {
                        speaker: cols[12],
                        avatar: cols[13],
                        expression: cols[14],
                        chinese: cols[15],
                        pinyin: cols[16] || "Autogenerated",
                        japanese: cols[17]
                    }
                ],
                notes: cols[13] || ""
            };

            chunkData.push(phraseObj);
            globalCounter++;
        }

        if (chunkData.length > 0) {
            const outPath = path.join(outDir, `chunk_${chunkNumber}.json`);
            fs.writeFileSync(outPath, JSON.stringify(chunkData, null, 2), 'utf-8');
            console.log(`Compiled ${outPath} with ${chunkData.length} phrases.`);
        }
    }
}

compileTSV();
