const fs = require('fs');
const path = require('path');

const phrasesDir = path.join(__dirname, '../src/data/phrases');

const subjects = [
    { c: '我', p: 'Wǒ', j: '私' }, { c: '你', p: 'Nǐ', j: 'あなた' }, { c: '他', p: 'Tā', j: '彼' },
    { c: '我们', p: 'Wǒmen', j: '私たち' }, { c: '经理', p: 'Jīnglǐ', j: 'マネージャー' }, { c: '客户', p: 'Kèhù', j: 'お客様' },
    { c: '大家', p: 'Dàjiā', j: 'みんな' }, { c: '公司', p: 'Gōngsī', j: '会社' }, { c: '朋友', p: 'Péngyou', j: '友達' },
    { c: '老板', p: 'Lǎobǎn', j: '社長' }
];

const verbs = [
    { c: '去', p: 'qù', j: '行く' }, { c: '做', p: 'zuò', j: 'する' }, { c: '买', p: 'mǎi', j: '買う' },
    { c: '吃', p: 'chī', j: '食べる' }, { c: '看', p: 'kàn', j: '見る' }, { c: '听', p: 'tīng', j: '聞く' },
    { c: '告诉', p: 'gàosu', j: '教える' }, { c: '需要', p: 'xūyào', j: '必要とする' }, { c: '了解', p: 'liǎojiě', j: '理解する' },
    { c: '喜欢', p: 'xǐhuan', j: '好きだ' }, { c: '觉得', p: 'juéde', j: '思う' }, { c: '准备', p: 'zhǔnbèi', j: '準備する' }
];

const objects = [
    { c: '工作', p: 'gōngzuò', j: '仕事', cat: 'business' }, { c: '饭', p: 'fàn', j: 'ご飯', cat: 'daily' },
    { c: '电影', p: 'diànyǐng', j: '映画', cat: 'daily' }, { c: '合同', p: 'hétong', j: '契約書', cat: 'business' },
    { c: '衣服', p: 'yīfu', j: '服', cat: 'daily' }, { c: '问题', p: 'wèntí', j: '問題', cat: 'business' },
    { c: '电脑', p: 'diànnǎo', j: 'パソコン', cat: 'daily' }, { c: '计划', p: 'jìhuà', j: '計画', cat: 'business' },
    { c: '资料', p: 'zīliào', j: '資料', cat: 'business' }, { c: '风景', p: 'fēngjǐng', j: '景色', cat: 'travel' }
];

const timeWords = [
    { c: '明天', p: 'Míngtiān', j: '明日' }, { c: '现在', p: 'Xiànzài', j: '今' }, { c: '今天', p: 'Jīntiān', j: '今日' },
    { c: '下午', p: 'Xiàwǔ', j: '午後' }, { c: '周末', p: 'Zhōumò', j: '週末' }, { c: '下周', p: 'Xià zhōu', j: '来週' }
];

const adjectives = [
    { c: '很好', p: 'hěn hǎo', j: 'とても良い' }, { c: '太贵了', p: 'tài guì le', j: '高すぎる' },
    { c: '非常重要', p: 'fēicháng zhòngyào', j: '非常に重要だ' }, { c: '很漂亮', p: 'hěn piàoliang', j: 'とても綺麗だ' }
];

const structures = [
    (s, v, o, t, a) => ({
        c: `${t}，${s}${v}${o.c}。`, p: `${t.p}, ${s.p} ${v.p} ${o.p}.`, j: `${t.j}、${s.j}は${o.j}を${v.j}。`, cat: o.cat,
        n: `頻繁に使う表現です。相手に物事をスッキリ伝えることができますよ！`
    }),
    (s, v, o, t, a) => ({
        c: `${s}觉得${o.c}${a.c}。`, p: `${s.p} juéde ${o.p} ${a.p}.`, j: `${s.j}は、${o.j}が${a.j}と思います。`, cat: o.cat,
        n: `「我觉得〜」は感想を伝える万能表現！絶対に覚えておきましょう。`
    }),
    (s, v, o, t, a) => ({
        c: `请问，${s}可以${v}${o.c}吗？`, p: `Qǐngwèn, ${s.p} kěyǐ ${v.p} ${o.p} ma?`, j: `すみません、${s.j}は${o.j}を${v.j}ことができますか？`, cat: o.cat,
        n: `「可以〜吗」は何かをお願いしたり、許可を取るときに一番自然な言い回しです。`
    }),
    (s, v, o, t, a) => ({
        c: `如果不${v}${o.c}，会怎么样？`, p: `Rúguǒ bù ${v.p} ${o.p}, huì zěnmeyàng?`, j: `もし${o.j}を${v.j}しないと、どうなりますか？`, cat: o.cat,
        n: `仮定の話をするときに使います。リスクを確認する場合などビジネスでも役立ちます。`
    })
];

let generatedSet = new Set();
let allNewPhrases = [];
function getRandom(arr) { return arr[Math.floor(Math.random() * arr.length)]; }

let idCounter = 1601;

while (allNewPhrases.length < 1400) { // chunks 33-60 x 50 phrases = 1400
    const s = getRandom(subjects);
    const v = getRandom(verbs);
    const o = getRandom(objects);
    const t = getRandom(timeWords);
    const a = getRandom(adjectives);
    const struct = getRandom(structures);
    const phrase = struct(s, v, o, t, a);

    if (!generatedSet.has(phrase.c)) {
        generatedSet.add(phrase.c);

        let av1 = getRandom(['panda', 'dog', 'cat', 'me', 'sensei']);
        let ex1 = getRandom(['normal', 'happy', 'sad']);
        let av2 = getRandom(['panda', 'dog', 'cat', 'me', 'sensei']);
        let ex2 = getRandom(['normal', 'happy', 'sad']);

        allNewPhrases.push({
            id: `phrase_gen_${String(idCounter).padStart(4, '0')}`,
            chinese: phrase.c,
            pinyin: phrase.p,
            japanese: phrase.j,
            category: phrase.cat,
            level: Math.floor(Math.random() * 3) + 1,
            example: [
                {
                    speaker: "A", avatar: av1, expression: ex1,
                    chinese: `关于这件事，${phrase.c}`, pinyin: "Autogenerated", japanese: `この件についてですが、${phrase.j}`
                },
                {
                    speaker: "B", avatar: av2, expression: ex2,
                    chinese: `我明白了。`, pinyin: "Autogenerated", japanese: `わかりました。`
                }
            ],
            notes: phrase.n
        });
        idCounter++;
    }
}

for (let c = 33; c <= 60; c++) {
    const startIndex = (c - 33) * 50;
    const chunkData = allNewPhrases.slice(startIndex, startIndex + 50);
    const outPath = path.join(phrasesDir, `chunk_${String(c).padStart(3, '0')}.json`);
    fs.writeFileSync(outPath, JSON.stringify(chunkData, null, 2), 'utf-8');
    console.log(`Generated automated chunk ${c} with ${chunkData.length} phrases.`);
}

console.log('Final phrases generation complete.');
